POST http://localhost:3000/api/tracks
Content-Type: application/json

{
  "name": "Money",
  "album": "Dark Side of the Moon",
  "artist": "Pink Floyd",
  "duration": 5.5,
  "cover": "https://upload.wikimedia.org/wikipedia/en/3/3b/Dark_Side_of_the_Moon.png"
}

####

POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Pedro Perez",
  "email": "pedro@example.com",
  "password": "12345678"
}